import { Roboto } from "next/font/google"; // Import Roboto font
import "./globals.css";
import Layout from "./components/layout";

// Configure the Roboto font
const roboto = Roboto({
  variable: "--font-roboto", // CSS variable for the font
  subsets: ["latin"], // Specify the subset
  weight: ["400", "500", "700"], // Add the weights you need (regular and bold in this case)
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} antialiased`}>
        {" "}
        {/* Apply Roboto font */}
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
